version: 2

jobs:
  build:
    docker:
      - image: redjays/xenial:dkms-build
    working_directory: /project
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: load keyring
          command: ./loadkey.sh
      - run:
          name: submit iomemory-vsl dkms build
          command: ./build.sh
